apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: postgres-example
build:
  artifacts:
  - image: edge-node-react-postgres-contacts-backend
    context: ../edge-node-react-postgres-contacts/backend
    sync:
      infer:
      - '**/*'
  - image: edge-node-react-postgres-contacts-frontend
    context: ../edge-node-react-postgres-contacts/frontend
    sync:
      infer:
      - '**/*'
deploy:
  kubectl:
    manifests:
    - ./k8s/*
# portForward:
# - resourceType: service
#  resourceName: edge-node-react-postgres-contacts-frontend
#  port: 80
#  address: 0.0.0.0
#  localPort: 4503