apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    tier: frontend
spec:
  type: NodePort
  selector:
    app: frontend
    tier: frontend
  ports:
  - port: 3000
    targetPort: http-server
    nodePort: 30465