apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-node-react-postgres-contacts-backend2
  labels:
    app: edge-node-react-postgres-contacts
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-node-react-postgres-contacts
      tier: backend
  template:
    metadata:
      labels:
        app: edge-node-react-postgres-contacts
        tier: backend
    spec:
     initContainers:
        # Need to replace Mongo with Postgres
      - name: init-db-ready
        image: postgres:12
        command: ['/bin/sh', '-c']
        args:
          - echo "Waiting for mongodb to start...";until (mongo --host nodejs-contacts-mongodb:27017 >/dev/null 2>&1) do echo "Waiting for connection for 2 sec."; sleep 2; done
     containers:
      - name: "edge-node-react-postgres-contacts-backend2"
        image: "edge-node-react-postgres-contacts-backend2"
        ports:
        - name: http-server
          containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: DB_HOST
          value: ""
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: ""
        - name: DB_USER
          value: ""     
        - name: DB_PASSWORD
          value: ""
        resources:
          requests:
            cpu: "200m"
            memory: "300Mi"
          # limits:
          #   cpu: "500m"            
          #   memory: "600Mi"  