apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
  template:
    metadata:
      labels:
        app: backend
        tier: backend
    spec:
     initContainers:
      - name: init-db-ready
        image: busybox
        command: ['sh', '-c', 'until nc -z -v -w30 contacts-db.pgo.svc.cluster.local 30435; do echo "Waiting for database connection..."; sleep 5; done;']
     containers:
      - name: "edge-node-react-postgres-contacts-backend2"
        image: backend:0.1
        ports:
        - name: http-server
          containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: DB_HOST
          value: "contacts.pgo.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: "contacts"
        - name: DB_USER
          value: "pguser"
        - name: DB_PASSWORD
          value: "password"