apiVersion: v1
kind: Service
metadata:
  name: edge-node-react-postgres-contacts-frontend
  labels:
    app: edge-node-react-postgres-contacts
    tier: frontend
spec:
  type: NodePort
  selector:
    app: edge-node-react-postgres-contacts
    tier: frontend
  ports:
  - port: 3000
    targetPort: http-server
    nodePort: 30455