apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      containers:
      - name: edge-node-react-postgres-contacts-frontend
        image: frontend:1.0
        ports:
        - name: http-server
          containerPort: 3000
        env:
        - name: PORT
          value: "3000"