
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      containers:
      - name: edge-node-react-postgres-contacts-frontend
        image: frontend:1.0
        ports:
        - name: http-server
          containerPort: 9090
        env:
        - name: PORT
          value: "4000"
        - name: REACT_APP_SERVER_URL
          value: backend:4000/contacts
